### ISSUE TITLE
可以实现维度成员的修改么？

### ISSUE THREAD

**Issue by yxq-coder** [EuclidOLAP/EuclidOLAP#121]
有了度量数据之后，可以实现维度成员的修改调整么？

**Comment by yxq-coder** [comment]
问题一：组织架构发生变动，维度成员可能会发生调整，也可能会删除某成员，比如A节点下的A1可能会移动到B节点下，也可能会把A2节点删除，希望能提供某种方案，让成员能支持update与delete。删除成员后，相关cube的度量值也能自动清除
问题二：度量值可以支持删除操作么？

**Comment by EuclidOLAP** [comment]
维度结构调整功能以后添加。
删除度量可以执行类似下面的语句：
再次执行insert更新值
insert [Airline A]
([Classes of Service].[Economy Plus], [Aircraft Models].[Airbus].[A318], Date.Calendar.[2022].[Q1].M2 Measures Revenue 888 Cost 666);
通过insert Measures NULL删除
insert [Airline A]
([Classes of Service].[Economy Plus], [Aircraft Models].[Airbus].[A318], Date.Calendar.[2022].[Q1].M3 Measures NULL);

**Comment by yxq-coder** [comment]
OK
