### ISSUE TITLE
请问可以根据一致性哈希算法对插入的数据进行分片么？

### ISSUE THREAD

**Issue by yxq-coder** [EuclidOLAP/EuclidOLAP#132]
请问可以在服务端实现对数据进行分片存储么？通过类似于redis的哈希槽算法或者一致性哈希算法进行分片

**Comment by EuclidOLAP** [comment]
你是指哪种分片？是分布式时将度量数据插入到指定的工作节点？

**Comment by yxq-coder** [comment]
例如以下插入语句：
insert [在线商店]
([店铺类型].[ALL].[平台自营],[支付方式].[ALL].[信用卡],[商品].[ALL].[厨房和餐厅].[便当盒],[Calendar].[ALL].[2020].[Q1].[M1] measures [销售额] 10 )

[店铺类型].[ALL].[平台自营],[支付方式].[ALL].[信用卡],[商品].[ALL].[厨房和餐厅].[便当盒],[Calendar].[ALL].[2020].[Q1].[M1] 这个维度成员的组合，在整个集群中应该是具有唯一性的，如果在客户端指定向哪个工作节点插入度量数据，会不会在不同节点容易出现重复的数据，比如A节点有这条数据，B节点也有，聚合的时候这个有做处理么？

能否根据这些成员id的组合，然后通过一致性哈希算法自动指定往那个工作节点插入这个度量值，而不是手动指定

**Comment by EuclidOLAP** [comment]
按哈希的现在还不支持，目前最新代码里可以通过手动指定分片，在insert [cube]后加上-> worker id，像下面的：
insert [在线商店] -> 100
([店铺类型].[ALL].[平台自营],[支付方式].[ALL].[信用卡],[商品].[ALL].[厨房和餐厅].[便当盒],[Calendar].[ALL].[2020].[Q1].[M1] measures [销售额] 10 );
worker id在配置文件中设置，如果找不到对应的worker id就会随机分配

**Comment by yxq-coder** [comment]
好的，谢谢
