### ISSUE TITLE
Docs: Benchmarking vs competing systems

### ISSUE THREAD

**Issue by jordandakota** [EuclidOLAP/EuclidOLAP#146]
When deciding whether to use EuclidOLAP one should consider performance vs competing products.

Recommend benchmarking on same system, same size dataset vs the following systems:

eMondrian on Clickhouse

Kylin

SQL Server Analysis Services

**Comment by EuclidOLAP** [comment]
Yeah, your suggestion is very important, I am designing the benchmark case, but I think there are still parts of EuclidOLAP's performance that need to be optimized, and I will publish benchmark when EuclidOLAP's query performance is further improved to a satisfactory ability.
Thank you for the advice
