### ISSUE TITLE
数据量较大时，并发插入数据的性能似乎存在一些问题，能否借鉴jedox palo的机制进行如下方案优化？

### ISSUE THREAD

**Issue by yxq-coder** [EuclidOLAP/EuclidOLAP#203]
内存数据 = bin文件（已经保存的数据） + log文件（未保存的增量数据）

1、插入数据时：先把插入信息写入log文件，然后直接更新内存数据（此时不做其他的磁盘数据更新）

2、保存：可以配置凌晨定时保存，也可以通过客户端调用保存方法时进行保存。当执行保存时，把内存中完整的数据映射到bin文件中，同时删掉log文件

3、重启时：先加载bin文件到内存中，如果有log文件，再把log文件中的增量数据更新到内存中

**Comment by EuclidOLAP** [comment]
这几天我会增加一个专门用于重新加载度量数据的命令。
你建的cube关联了几个维度？总共插入了多少明细度量数据？

**Comment by yxq-coder** [comment]
关联有14个维度，明细数据有千万条，提交一张报表，可能要插入十万行明细数据，要支持并发提交报表

**Comment by EuclidOLAP** [comment]
1、在执行插入度量的MDX语句时可以使用DISABLE_RELOAD_MEASURES选项来表示只是将数据追加到磁盘文件而不加载到内存，如下：
insert [Airline A] -> 1
DISABLE_RELOAD_MEASURES
( [Aircraft Models].[Airbus].[A318], [Date].[2019].[Q1].[M1]. ... ...

2、在数据追加到内存后可以手动执行RELOAD命令将磁盘中的度量数据重构到内存，如下：
reload <Cube_name>;
执行reload命令时，新的度量数据将在内存中被重新构建为动态索引结构，但同时旧的数据并不会被立即卸载，当新的数据够建完毕后将会立即替换掉旧数据。

3、代码已经提交了，你可以找v0.1.6-beta这个release，或者使用docker镜像：
docker run -d -p 8760:8760 --name olap-016 euclidolap/euclidolap:v0.1.6-beta

4、这只是个临时方案，关于度量数据的增删改具体功能在未来会基于弹性资源、云环境和存储与计算分离的架构去重新规划。
